- name: "Installing docker package"
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: "Checking if docker was started and enabled"
  service:
    name: docker
    state: started
    enabled: yes